# Generated by Django 3.1.4 on 2020-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField(choices=[(1, 'BOLSA MEXICANA'), (2, 'BANXICO'), (3, 'FIXER')], verbose_name='source')),
                ('rate', models.FloatField(verbose_name='rate')),
                ('date', models.DateField(verbose_name='date')),
                ('last_update', models.DateTimeField(verbose_name='last_update')),
            ],
            options={
                'verbose_name': 'currency exchange',
                'verbose_name_plural': 'currencies exchange',
            },
        ),
    ]
